### ISSUE TITLE
Warning: "default" filter used without specifying the type of comparison

### ISSUE THREAD

**Issue by joelanman** [pkolt/express-nunjucks#2]
I'm also getting this warning:

> [nunjucks] Warning: the "default" filter was used without specifying the type of comparison. 2.0 changed the default behavior from boolean (val ? val : def) to strictly undefined, so you should make sure that doesn't break anything. Be explicit about this to make this warning go away, or wait until 2.1. See http://mozilla.github.io/nunjucks/templating.html#defaultvalue-default-boolean

from that URL:

> default(value, default, [boolean])
>
> (aliased as d)
>
> If value is strictly undefined, return default, otherwise value. If boolean is true, any JavaScript falsy value will return default (false, "", etc)

> In version 2.0, this filter changed the default behavior of this filter. Previously, it acted as if boolean was true by default, and any falsy value would return default. In 2.0 the default is only an undefined value returns default. You can get the old behavior by passing true to boolean, or just use value or default. 2.0 will show a warning if boolean is not passed, but we will remove this warning in the next version.

**Comment by pkolt** [comment]
They will remove this warning in next version nunjucks.

Now you can use:
```html
<h1>{{ title|d('My site', true) }}</h1>
```
or
```html
<h1>{{ title|d('My site', false) }}</h1>
```
or
```html
<h1>{{ title or 'My site' }}</h1>
``` 

The details are in the source code https://github.com/mozilla/nunjucks/blob/v2.1.0/src/filters.js#L68
