### ISSUE TITLE
Expose nunjucks object

### ISSUE THREAD

**Issue by rickysullivan** [pkolt/express-nunjucks#4]
While trying to add a custom filter. I getting an error `Cannot read property 'SafeString' of undefined` because `nunjucks` want defined.

```
const nunjucksExpress = require('express-nunjucks');

...

nunjucksExpress.ready().then(function (env) {
    env.addFilter('inspect', function (data) {
        return new nunjucksExpress.nunjucks.runtime.SafeString('<pre><code>' + JSON.stringify(data, undefined, 2) + '</code></pre>');
    });
});
```

I have submitted a PR: #3 
No sure if that's the correct way. Happy to discuss.

**Comment by pkolt** [comment]
You can use:

```javascript
const nunjucksExpress = require('express-nunjucks');
const nunjucks = require('nunjucks');

...

nunjucksExpress.ready().then(function (env) {
    env.addFilter('inspect', function (data) {
        return new nunjucks.runtime.SafeString('<pre><code>' + JSON.stringify(data, undefined, 2) + '</code></pre>');
    });
});
```

**Comment by rickysullivan** [comment]
That means I need to add Nunjucks as a dependency to my project. I think it would be better to expose the same nunjucks module being used over having multiple instances of nunjucks? What if there were discrepancies in the versions?
